#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jan 02 00:23:27 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=12
shaderPack=iterationT 3.2.0.zip
